### ISSUE TITLE
Automation framework detected by pixelscan

### ISSUE THREAD

**Issue by Somberor** [berstend/puppeteer-extra#324]
hey guys , 
any idea how can pixelscan.net detect my puppeteer even with stealth on?
http://prntscr.com/uhs1aq

This is a sample of the code:
`const puppeteer = require('puppeteer-extra');

    const pluginStealth = require('puppeteer-extra-plugin-stealth');

    puppeteer.use(pluginStealth());

    let isheadless = false;
    let browser2 = await puppeteer.launch({
        headless: isheadless,
        //ignoreHTTPSErrors: true,
        //executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
        args: []
    });
    let page2 = (await browser2.pages())[0];`

Is it possible to add/modify more variables manually to make the browser even less detectable?
thank you!

**Comment by trnj** [comment]
The most valuable part that is the bottom of this screenshot.  

There are could be issues with screen res, gl vendors, incorrect timezone.

It is not related to the plugin itself, imho.

**Comment by trnj** [comment]
Btw pixel scan uses a bit old lib for detection, which is not relevant to up to date providers.

**Comment by prescience-data** [comment]
@trnj I haven't looked at it myself, but I'm assuming they check the pixel overhang on this right?

### Real Browser
![image](https://user-images.githubusercontent.com/65471523/93292898-04bc8500-f82a-11ea-8341-90d02ccfb443.png)


### Puppeteer Extra Stealth 2.6.1
(Available screen size +40 pixels)
![image](https://user-images.githubusercontent.com/65471523/93292879-f5d5d280-f829-11ea-94b3-f21f1f83947f.png)

**Comment by trnj** [comment]
There is a bug in 2.6.1... so wait for the next release or downgrade to 2.6.0.

Experiment with vendor gl, I think your settings are not correct. Compare with a real browser. Also, check plugins, should be chrome not chromium. 

Match your settings from the real browser with headless.

**Comment by Niek** [comment]
@prescience-data yes that would be a good one to add. Although I'm not sure it's causing it in this case.

**Comment by trnj** [comment]
In this case, it is detected by vendor webgl settings, if I remember correctly.  
I bypassed this test.

**Comment by Niek** [comment]
> There is a bug in 2.6.1... so wait for the next release or downgrade to 2.6.0.

Can you elaborate what bug you are referring to @trnj? Is it the plugins detection (must be since that's the only thing that changed between 2.6.0 and 2.6.1)?

Can you check if it's fixed with my PR applied? #312

**Comment by trnj** [comment]
Ok, I've finally found the reason. 

If I disable `'iframe.contentWindow'` on 2.6.0, this test fails. 
Btw, I disable it because of the redirect problem described here https://github.com/berstend/puppeteer-extra/issues/202#issuecomment-643433111 
Has it been resolved yet?

Web gl is related to another issue, not pixel scan. 

TS probably uses 2.6.1 which fails due to the bug. I think you can close this issue since 2.6.0 passes the test.

**Comment by Niek** [comment]
@trnj can you check my previous comment and see if it works with 2.6.1 + my PR applied?

**Comment by trnj** [comment]
Still the same on 2.6.1, even with proposed fix.  Without iframe.contentWindow passes the test.

**Comment by trnj** [comment]
Well, I've probably solved the issue with `iframe.contentWindow`

https://github.com/berstend/puppeteer-extra/issues/137#issuecomment-693378136

If someone knows how to test it correctly, then pm.

**Comment by trnj** [comment]
Now I can pass the test with a full pack of plugins.

But the way, I think the Puppeteer team has fixed the described issue in the comment. 

berstend implemented the solution proposed in the comment of #137 
However, this solution is incorrect.

**Comment by Niek** [comment]
Looking forward to see the PR with the fix @trnj

**Comment by trnj** [comment]
> Looking forward to see the PR with the fix @trnj

Just add here 
https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.js

The following

```
          const contentWindowProxy = {
            get(target, key) {
              // Now to the interesting part:
              // We actually make this thing behave like a regular iframe window,
              // by intercepting calls to e.g. `.self` and redirect it to the correct thing. :)
              // That makes it possible for these assertions to be correct:
              // iframe.contentWindow.self === window.top // must be false
              if (key === 'self') {
                return this
              }
 **if (key === 'document') {
 return iframe.contentDocument || iframe.contentWindow.document;
 }**
              // iframe.contentWindow.frameElement === iframe // must be true
              if (key === 'frameElement') {
                return iframe
              }
              return Reflect.get(target, key)
            }
          }

```

This would fix the problem with iframe redirect and the plugin will pass this test out of the box.

**Comment by brunogaspar** [comment]
You can add it yourself through a pull request :)

**Comment by trnj** [comment]
Just 2 lines... 

Well, ifov is still not solved in 2.1.6... that is very sad... were so much hope :(

**Comment by Niek** [comment]
PR @ https://github.com/berstend/puppeteer-extra/pull/327, closing this

**Comment by Niek** [comment]
New PR: https://github.com/berstend/puppeteer-extra/pull/341
